# NumPy



In [3]:
import numpy as np

### Basic Array Creation

In [5]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [6]:
arr1 = np.array([1,2.4,"Hello"])
print(arr1)

['1' '2.4' 'Hello']


In [8]:
np.array(arr1)

array(['1', '2.4', 'Hello'], dtype='<U32')

In [9]:
arr1 = np.array([1,2.4])
np.array(arr1)

array([1. , 2.4])

In [10]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
print(list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [11]:
np.array(list1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array Generation Function

In [15]:
arr2 = np.arange(1,11)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
arr3 = np.zeros(6)
print(arr3)

[0. 0. 0. 0. 0. 0.]


In [20]:
arr3 = np.zeros((3,6))
print(arr3)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [21]:
arr4 = np.ones(6)
print(arr4)

[1. 1. 1. 1. 1. 1.]


In [6]:
arr = np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


### Random Generation function

In [7]:
arr1 = np.random.rand(5) # 0 to 1
print(arr1)

[0.08057576 0.9475482  0.14124834 0.28913761 0.27320901]


In [11]:
arr2 = np.random.randn(10) # -3 to 3
print(arr2)

[ 0.11371716  0.6046208  -1.4435516  -2.59447273  1.21092747  0.23345049
 -1.35596248 -1.15190673 -0.60626416  1.43920283]


In [16]:
arr4 = np.random.randint(10,20,10)
print(arr4)

[10 19 18 14 13 16 11 14 11 10]


### Array Attributes

In [4]:
arr6 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
arr6.shape

(3, 4)

In [7]:
arr6.dtype

dtype('int64')

### Array Methods

In [8]:
arr6.min()

np.int64(1)

In [9]:
arr6.max()

np.int64(12)

In [10]:
arr6.sum()

np.int64(78)

In [13]:
print(np.sum(arr6,axis = 0)) # column wise 

[15 18 21 24]


In [14]:
print(np.sum(arr6,axis = 1))

[10 26 42]


In [15]:
print(arr6.mean())

6.5


In [16]:
print(arr6.std())

3.452052529534663


In [17]:
arr6.argmin()

np.int64(0)

In [20]:
arr6.argmax()

np.int64(11)

### Reshaping and Resizing

In [23]:
arr_temp = np.arange(1,31)
arr_temp.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [26]:
arrt = np.arange(11,21)
print(arrt)

[11 12 13 14 15 16 17 18 19 20]


In [29]:
print(arrt[6])

17


In [31]:
print(arrt[1:5])

[12 13 14 15]


### Numpy indxing and slicing of matrix

In [36]:
arr2 = np.arange(1,26).reshape(5,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [37]:
print(arr2[0])

[1 2 3 4 5]


In [40]:
print(arr2[0,0])

1


In [41]:
print(arr2[0:2,1:3])

[[2 3]
 [7 8]]


In [43]:
print(arr2[2:,3:])

[[14 15]
 [19 20]
 [24 25]]


In [44]:
print(arr2[:,2])

[ 3  8 13 18 23]


### Boolean indexing 

In [45]:
arr = np.arange(11,21)
bool_index = arr%2 == 0
print(bool_index)

[False  True False  True False  True False  True False  True]


In [46]:
arr = arr[bool_index]

In [47]:
print(arr)

[12 14 16 18 20]


## Array Opearations

### Arithmetic oprations


In [6]:
a1 = np.array([23,78,90,12,34])
a2 = np.array([25,68,45,2,14])
arr2 = a1 + a2
print(arr2)

[ 48 146 135  14  48]


### Broadcasting

In [9]:
l = [10,20,30,40]
arr = np.array(l)
print(arr + 10)

[20 30 40 50]


### Deep and Shallow copy

In [10]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
slice = a[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [16]:
# deep copy 
b = a
b[0] = 11
a

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
c = b.copy()


In [18]:
c[0] = 12
c

array([12,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
b

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Matrix Operation

In [21]:
matx = np.array([[4,5],[6,7]])
matx2 = np.array([[9,10],[1,2]])

print(matx + matx2)

[[13 15]
 [ 7  9]]


In [22]:
print(matx @ matx2)

[[41 50]
 [61 74]]


In [23]:
print(matx)

[[4 5]
 [6 7]]


In [24]:
print(matx2)

[[ 9 10]
 [ 1  2]]


In [25]:
print(np.dot(matx,matx2))

[[41 50]
 [61 74]]


In [27]:
print(matx.T)

[[4 6]
 [5 7]]


### Advance Array Manipulation

In [28]:
# Stacking Array
# normal
# vertical
# horizontal

In [29]:
a1 = np.array([23,78,90,12,34])
a2 = np.array([25,68,45,2,14])


In [30]:
np.vstack((a1,a2))

array([[23, 78, 90, 12, 34],
       [25, 68, 45,  2, 14]])

In [32]:
np.hstack((a1,a2))

array([23, 78, 90, 12, 34, 25, 68, 45,  2, 14])

In [33]:
np.column_stack((a1,a2))

array([[23, 25],
       [78, 68],
       [90, 45],
       [12,  2],
       [34, 14]])

### Splitting Array

In [39]:
sarr = np.arange(16).reshape(4,4)
print(sarr)
print("Horizonal Split Array:")
print(np.hsplit(sarr,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Horizonal Split Array:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [54]:
v_split = np.vsplit(sarr,4)
for i in v_split:
    print(i,"\n")

[[0 1 2 3]] 

[[4 5 6 7]] 

[[ 8  9 10 11]] 

[[12 13 14 15]] 



#### Exersise

In [55]:
# valid Sudoku

In [2]:
import numpy as np

In [3]:
sarr = np.array( [
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
    ]
)

In [15]:
row_sum = np.sum(sarr,axis = 1)
print(row_sum)
row_sum == 45
for i in row_sum:
    if i != 45:
        print("Sudoku is not valid!")
        break
else:
    print("Sudoku is valid!")

[45 45 45 45 45 45 45 45 45]
Sudoku is valid!


In [14]:
col_sum = np.sum(sarr,axis = 0)
print(col_sum)
for i in col_sum:
    if i != 45:
        print("Sudoku is not valid!")
        break
else:
    print("Sudoku is valid!")

[45 45 45 45 45 45 45 45 45]
Sudoku is valid!


In [18]:
sarr[:3,:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [22]:
sarr[:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [24]:
sarr[:3,6:]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [25]:
sarr[3:6,:3]

array([[8, 5, 9],
       [4, 2, 6],
       [7, 1, 3]])

In [26]:
sarr[6:,:3]

array([[9, 6, 1],
       [2, 8, 7],
       [3, 4, 5]])

In [27]:
sarr[6:,3:6]

array([[5, 3, 7],
       [4, 1, 9],
       [2, 8, 6]])

In [29]:
sarr[6:,6:]

array([[2, 8, 4],
       [6, 3, 5],
       [1, 7, 9]])

In [33]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = sarr[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [21]:
# columns: [Age, Math Marks, Science Marks]

data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])
print(data)

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65 70]
 [20 90 85]]


In [58]:
print(data.shape)

(5, 3)


In [59]:
print(data[:,1])

[85 92 76 65 90]


In [65]:

print(np.max(data[:,2]))

95


In [66]:
np.mean(data[:,0])

np.float64(19.4)

In [62]:
data[data[:,1] > 90]


array([[19, 92, 88]])

In [71]:
data[:,1]  += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [77]:
print(len(data[data[:,0] < 19]))

3


In [4]:
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [9]:
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [23]:
# replace all science marks < 75 with 0

data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])